name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Mona
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "${FIRST_NAME}"
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
#          pass: ${{ secrets.PASS }}